[package]
name = "jsonrpsee"
description = "JSON-RPC crate"
version = "0.2.0-alpha.4"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
http-client = { path = "../http-client", version = "0.2.0-alpha.4", package = "jsonrpsee-http-client" }
http-server = { path = "../http-server", version = "0.2.0-alpha.4", package = "jsonrpsee-http-server" }
ws-client = { path = "../ws-client", version = "0.2.0-alpha.4", package = "jsonrpsee-ws-client" }
ws-server = { path = "../ws-server", version = "0.2.0-alpha.4", package = "jsonrpsee-ws-server" }
types = { path = "../types", version = "0.2.0-alpha.4", package = "jsonrpsee-types" }
utils = { path = "../utils", version = "0.2.0-alpha.4", package = "jsonrpsee-utils" }
proc-macros = { path = "../proc-macros", version = "0.2.0-alpha.4", package = "jsonrpsee-proc-macros" }

[dev-dependencies]
env_logger = "0.8"
futures = "0.3"
log = "0.4"
test-utils = { path = "../test-utils", version = "0.2.0-alpha.4", package = "jsonrpsee-test-utils" }
tokio = { version = "1", features = ["full"] }
